backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "portfolio"
    label: "Portafolio"
    files:
      - name: "galeria"
        label: "Galeria de Fotografias"
        file: "fotos.json"
        fields:
          - label: "Fotos"
            name: "fotos"
            widget: "list"
            fields:
              - { label: "Título de la Foto", name: "title", widget: "string" }
              - { label: "Categoría", name: "category", widget: "select", options: [
                  { label: "Retratos", value: "retratos" },
                  { label: "Eventos", value: "eventos" },
                  { label: "Corporativo", value: "corporativo" }
                ]}
              - { label: "Etiqueta (Tag)", name: "tag", widget: "string", default: "Portafolio" }
              - { label: "Archivo de Imagen", name: "img", widget: "image" }
